"""empty message

Revision ID: 52f59a192d68
Revises: 
Create Date: 2020-10-04 21:45:40.764838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f59a192d68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('contacts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('dialog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('personal', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_id'), 'dialog', ['id'], unique=False)
    op.create_index(op.f('ix_dialog_name'), 'dialog', ['name'], unique=True)
    op.create_index(op.f('ix_dialog_personal'), 'dialog', ['personal'], unique=False)
    op.create_table('association_table',
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unread', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_association_table_dialog_id'), 'association_table', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_association_table_unread'), 'association_table', ['unread'], unique=False)
    op.create_index(op.f('ix_association_table_user_id'), 'association_table', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialog.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_dialog_id'), 'message', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_dialog_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_association_table_user_id'), table_name='association_table')
    op.drop_index(op.f('ix_association_table_unread'), table_name='association_table')
    op.drop_index(op.f('ix_association_table_dialog_id'), table_name='association_table')
    op.drop_table('association_table')
    op.drop_index(op.f('ix_dialog_personal'), table_name='dialog')
    op.drop_index(op.f('ix_dialog_name'), table_name='dialog')
    op.drop_index(op.f('ix_dialog_id'), table_name='dialog')
    op.drop_table('dialog')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
