"""empty message

Revision ID: 7357a07fd916
Revises: 52f59a192d68
Create Date: 2020-10-06 18:48:09.743137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7357a07fd916'
down_revision = '52f59a192d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dialog_name', table_name='dialog')
    op.create_index(op.f('ix_dialog_name'), 'dialog', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialog_name'), table_name='dialog')
    op.create_index('ix_dialog_name', 'dialog', ['name'], unique=1)
    # ### end Alembic commands ###
