"""empty message

Revision ID: eac4d9095c11
Revises: 6fc499d59a6f
Create Date: 2021-02-01 18:24:05.881837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac4d9095c11'
down_revision = '6fc499d59a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dialog_personal', table_name='dialog')
    op.drop_column('dialog', 'personal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('personal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_dialog_personal', 'dialog', ['personal'], unique=False)
    # ### end Alembic commands ###
